TurnTable/TurnTable/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('turn/',include('turn.urls')),
]

TurnTable/turn/urls.py
from django.urls import path
import django.conf.urls 
from . import views
# from django.views.decorators.csrf import csrf_exempt


app_name = 'turn'
urlpatterns = [
    path('', views.index, name='index'),
    path('draw',views.draw, name = 'draw'),
    path('rotate',views.rotate, name = 'rotate'),
    path('no_prize',views.no_prize, name ='no_prize'),
    path('exist',views.exist, name = 'exist'),
    
]

TurnTable/turn/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Prize(models.Model):
    name = models.CharField(max_length= 200)
    prize_id = models.IntegerField(default= 0)
    quantity = models.IntegerField(default= 0)

    def __str__(self):
        return self.name

class User(models.Model):
    phone = models.CharField( max_length= 200)
    prizeWin = models.IntegerField(default= 0)
    isDraw = models.BooleanField(default= False)

    def __str__(self):
        return self.phone

TurnTable/turn/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect,JsonResponse
from django.template import loader
from .models import Prize
from .models import User
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import random

# Create your views here.
def index(request):
    return render(request,'turnTable/index.html')

#save the user phone and return 
def draw(request):
    
    if request.method == 'POST':
        
        phoneNum = request.POST.get("phone", "")
        context ={
            'phoneNum':phoneNum
        }
        #print(context)
        #check if the user already exist,not exist: save new user; exist: go to draw page directly
        if not User.objects.filter(phone=phoneNum):
           
            new_user = User(phone=phoneNum, prizeWin=0,isDraw=False)
            new_user.save()
            return render(request, 'turnTable/draw.html',context)
        else:
            return render(request, 'turnTable/draw.html',context)

def rotate(request):
    userPhone = str(request.POST.get('userPhone',""))
    prize = random.randrange(7)
    # user = get_object_or_404(User, pk=userPhone) 为啥不好用
    user =User.objects.get(phone=userPhone)
    #check if the user already drawed
    if user.isDraw == False:
        prizeWin = Prize.objects.get(prize_id=prize)
         #check the quantity of remaining prize, if the quantity is zero, then set prize tp 7 which is not winning
        if prizeWin.quantity > 0:
            prizeWin.quantity-=1
        else:
            prize =6
        user.prizeWin = prize
        #user.isDraw =True #make sure one user can only draw once
        user.save() #save the user info
        prizeWin.save() #update the prize quantity change
        response = {'userPhone':userPhone,"prize":prize,"isDraw":'no','quantity':prizeWin.quantity,'name':prizeWin.name}
        return JsonResponse(response)   
    else:
        prize =6
        response = {'userPhone':userPhone,"prize":prize,"isDraw":'yes'}
        return JsonResponse(response)   

def exist(request):
    return render(request,'turnTable/exist.html')

def no_prize(request):
    return render(request,'turnTable/no_prize.html')



    


TurnTable/turn/templates/turnTable/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>

	<title>梅賽德斯·奔馳-2018 Chinese New Year</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

		<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1, user-scalable=no, maximum-scale=1, height=device-height">
		<link rel="shortcut icon" type="image/png" href="{%static './turnTable/img/favicon.png' %}" />
		<link rel="stylesheet" type="text/css" media="screen" href="{%static './turnTable/css/style.css' %}" />
		
		<script src="http://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	</head>
	<body>
		<header>
			<img src="{% static './turnTable/img/logo.png' %}" alt="Mercedes-Benz">
		</header>

        {%block content%}

        {% endblock %}

		<footer>
			<p>Copyright &copy; Mercedes-Benz Vancouver Retail Group</p>
			<!-- <p><a href="http://thinko.ca/">Powered by Thinko Technology LTD.</a></p> -->
		</footer>



        {%block scripts%}
        {% endblock %}
	</body>
</html>

TurnTable/turn/templates/turnTable/draw.html
{% extends "./base.html" %} {% load static %} {% block content%}
<main>
    <div id='DrawThePrize'>
        <h3>梅賽德斯·奔馳 祝您</h3>
        <h1>新春快樂!</h1>
    
        <form action="{% url 'turn:rotate' %}" id='rotate' method='POST'>
        
            {% csrf_token %}
            <div class="turntable-wrapper">
                <div id="turntable-bg">
                    <input type = 'hidden' name="userPhone" value="{{phoneNum}}" />
                    <img src="{% static './turnTable/img/pointer.png' %}" alt="pointer" class="pointer" onclick="rotate()">
                    <img src="{% static './turnTable/img/turntable.png' %}" alt="turntable"  class="turntable-base">
                </div>
            </div>
        </form>
    
    
        <h2>請點擊上方轉盤中央“開始抽獎”字樣進行抽獎</h2>
        <p>每個手機號碼僅能進行一次抽獎，敬請理解。</p>
        <div id="content">
            <div class="input-wrapper blue">
                
                
                <p class="input">您輸入的手機號碼為: <span id="userPhone" >{{phoneNum}}</span></p>
            </div>
        </div>
    </div>
    <!-- ---------------------------------------------------------------------------------------- -->
    <div id='winThePrize'class="main-img-wrapper" style="background-image: url({% static 'turnTable/img/prize.jpg' %}); width: 100%; display:none">
        
        <div>
        <h2 class="red">恭喜中獎！您贏得了 <br><span id='PrizeName'> the prize name </span></h2>
        <p class="left"><br>展示圖片可能與實物不符，請以實物為準</p>
        <div id="content">
            <div class="input-wrapper red">
                <p class="input">您輸入的手機號碼為: {{phoneNum}}</p>
            </div>
        </div>
        </div>
    </div> 

    <!-- ---------------------------------------------------------------------------------------- -->		
    
    
</main>
{% endblock %} 

{%block scripts%}

<script src="{%static './turnTable/js/main.js' %}" defer></script>

{% endblock%}

TurnTable/turn/templates/turnTable/exist.html
{% extends "./base.html" %} {% load static %} {% block content%}
<main>
    <h3>梅賽德斯·奔馳 祝您</h3>
    <h1>新春快樂!</h1>
    <br>
    <h3 class="blue">很抱歉，每個手機號碼僅能進行一次抽獎。但這并不會影響您在新的一年滾滾而來的好運與財源，記得向店內索取一份紅包討個好彩頭吧！新年快樂！</h3>

    <!-- todo: chagne the style="background-image: url(...)" to the prize image -->
    <!-- we will get the prize by next week -->
    <div class="main-img-wrapper" style="background-image: url(img/c1.jpg)">
        <!-- use background to set the image -->
    </div>

    <script>
        //simple slider
        var i = 2;
        window.setInterval(function(){
        // $('.main-img-wrapper').attr('style', 'background-image: url(turntable/static/turntable/img/c'+i+'.jpg)');
        $('.main-img-wrapper').attr('style', 'background-image: url("/static/turnTable/img/c'+i+'.jpg")');
        
          i+=1;
          if (i>5){
              i=1;
          }
        }, 3000);
    </script>
    
    
    <div id="content">
        <div>
            <a href="https://www.mercedes-benz-richmond.ca/" class="terms-btn">點擊查看奔馳新春特惠</a>
        </div>	
        
    </div>			
</main>
{% endblock %} 

TurnTable/turn/templates/turnTable/index.html
{% extends "./base.html" %} {% load static %} {% block content%}
<main>
  <div class="main-img-wrapper home-img-wrapper">
    <h3>梅賽德斯·奔馳 祝您</h3>
    <h1>新春快樂!</h1>
    <!-- use background to set the image -->
  </div>
  <h2>歡迎光臨梅賽德斯·奔馳 列治文店</h2>
  <div id="content">
    <!-- todo: if you want to submit using form -->
    <form id="userPhone" action="{% url 'turn:draw' %}" method='POST' onsubmit="return check()">
      <div class="input-wrapper blue">
        <input
          id="phone"
          name="phone"
          
          placeholder="請于此處填寫手機號碼以參與抽獎"
        />
        {%csrf_token%} {{form.as_p}}
      </div>
      <div>
        <button type="submit" class="btn home-btn">進入抽獎</button>
      </div>
      <div>
        <!-- todo:oscar add terms&condition link, if we have it -->
        <a
          href="https://www.mercedes-benz.ca/content/canada/mpc/mpc_canada_website/en/home_mpc/privacy_statement.ngrb.html"
          class="terms-btn"
          >活動條款</a
        >
      </div>
    </form>
  </div>
</main>
{% endblock %} {%block scripts%}

<script src="{%static './turnTable/js/phoneCheck.js' %}" defer></script>

{% endblock%}

TurnTable/turn/templates/turnTable/no_prize.html
{% extends "./base.html" %} {% load static %} {% block content%}
<main>
    <br>
    <h3 class="blue left">很抱歉，您沒有中獎。但這并不會影響您在新的一年滾滾而來的好運與財源。記得向店內索取一份紅包討個好彩頭吧！新年快樂！</h3>
    <br>
    <!-- todo: chagne the style="background-image: url(...)" to the prize image -->
    <!-- we will get the prize by next week -->
    <div class="main-img-wrapper" style="background-image: url(img/c1.jpg)">
        <!-- use background to set the image -->
    </div>
    <br>
    <script>
        //simple slider
        var i = 2;
        window.setInterval(function(){
          $('.main-img-wrapper').attr('style', "background-image: url(/static/turnTable/img/c"+i+".jpg);");
          i+=1;
          if (i>5){
              i=1;
          }
        }, 3000);
    </script>
    
    
    <div id="content">
        <div>
            <a href="https://www.mbvancouver.ca/new-vehicle-offers/" class="link-btn">點擊查看奔馳新春特惠</a>
        </div>	
        
    </div>			
</main>
{% endblock %}